const CANVAS_WIDTH = window.innerWidth - 100
const CANVAS_HEIGHT = window.innerHeight - 100

const SELECT_DELTA = 3
const SNAP_DELTA = 10
const MAX_NUM_ERROR = 1e-6

const ENTER_KEY_CODE = 13
const SPACE_KEY_CODE = 32
const ESCAPE_KEY_CODE = 27
const DELETE_KEY_CODE = 46

export {
    CANVAS_HEIGHT,
    CANVAS_WIDTH,
    SELECT_DELTA,
    SNAP_DELTA,
    MAX_NUM_ERROR,
    ENTER_KEY_CODE,
    SPACE_KEY_CODE,
    ESCAPE_KEY_CODE,
    DELETE_KEY_CODE
}